apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-openvino
spec:
  replicas: 3
  selector:
    role: model_server
  template:
    metadata:
      labels:
        role: model_server
    spec:
      containers:
      - name: openvino-model-server
        image: [your openvino model server image]
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        command: ["/ie-serving-py/start_server.sh"]
        args: ["ie_serving", "model", "--model_path", "/opt/ml/resnet", "--model_name", "resnet", "--port", "80"]
        ports:
          - name: grpc
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/opt/ml"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
